/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#d8e3fb",
        "on-surface": "#191c1d",
        "tertiary-fixed": "#dbe1ff",
        "surface-container-highest": "#e1e3e4",
        "surface-tint": "#bf0715",
        "on-primary-fixed-variant": "#93000b",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#003ea8",
        "tertiary-fixed-dim": "#b4c5ff",
        "tertiary": "#004ed0",
        "primary-fixed-dim": "#ffb4ab",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#410002",
        "on-error-container": "#93000a",
        "on-primary-container": "#fff6f5",
        "surface-variant": "#e1e3e4",
        "surface-container-high": "#e7e8e9",
        "secondary-fixed-dim": "#bcc7de",
        "inverse-on-surface": "#f0f1f2",
        "surface-container": "#edeeef",
        "outline-variant": "#e6bdb8",
        "primary-container": "#dc2626",
        "inverse-primary": "#ffb4ab",
        "surface-container-low": "#f3f4f5",
        "surface-dim": "#d9dadb",
        "on-error": "#ffffff",
        "surface": "#f8f9fa",
        "primary-fixed": "#ffdad6",
        "tertiary-container": "#2d68f0",
        "on-secondary-fixed": "#111c2d",
        "background": "#f8f9fa",
        "secondary": "#545f73",
        "error": "#ba1a1a",
        "secondary-container": "#d5e0f8",
        "surface-bright": "#f8f9fa",
        "on-tertiary-fixed": "#00174b",
        "on-primary": "#ffffff",
        "inverse-surface": "#2e3132",
        "on-tertiary-container": "#f8f7ff",
        "on-secondary-fixed-variant": "#3c475a",
        "primary": "#b70011",
        "on-surface-variant": "#5c403c",
        "on-background": "#191c1d",
        "on-secondary-container": "#586377",
        "outline": "#916f6b"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "4px",
        "xl": "32px",
        "md": "16px",
        "touch-target": "48px",
        "lg": "24px",
        "xs": "4px",
        "sm": "8px",
        "safe-margin": "20px"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "display-sos": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-sos": ["48px", { lineHeight: "56px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-bold": ["14px", { lineHeight: "20px", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
